language: python
sudo: required
python:
   - 3.6

before_install:
    - set -e  # fail on any error
    - sudo apt-get update -q

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install PyBM3D dependencies
  - sudo apt-get install libpng-dev
  - sudo apt-get install libjpeg-dev
  - sudo apt-get install libtiff-dev
  - sudo apt-get install libfftw3-dev

  - conda env create -f environment.yml
  - source activate scout
  - conda develop .
script:
   - pytest -s -v tests
