name: scout
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cython
  - h5py
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - matplotlib
  - numcodecs
  - numpy
  - pandas
  - pip
  - pyqt
  - python>=3.7
  - pytorch-nightly
  - pywavelets
  - pyyaml
  - pyzmq
  - scikit-image
  - scikit-learn
  - scipy
  - sphinx
  - tifffile
  - tornado=4.5.3
  - tqdm
  - pip:
    - lapsolver
    - mayavi
    - multicoretsne
    - pyqt5
    - seaborn

